# serverless.yml
service: demo-apollo-server-lambda
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  webpack:
    includeModules: true
