name: Deployment

on:
  push:
    branches:
      - main
      - attempt-deployment

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: deploy # will run `yarn install` command
