name: Deployment

on:
  push:
    branches:
      - main
      - attempt-deployment

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        run: yarn deploy
