name: Deploy

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Refs
        uses: rlespinasse/github-slug-action@v2.x

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: yarn install --frozen-lockfile

      - name: Serverless Deploy
        id: serverless_deploy
        run: npx serverless deploy --stage production --org=bradleftley
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MEDIA_URL: ${{ secrets.MEDIA_URL }}
          PLEX_META_URL: ${{ secrets.PLEX_META_URL }}
          PLEX_MOVIE_STUFF: ${{ secrets.PLEX_MOVIE_STUFF }}
          PLEX_TV_SHOW: ${{ secrets.PLEX_TV_SHOW }}
          PLEX_WATCH_LIST: ${{ secrets.PLEX_WATCH_LIST }}
